void error(long code);
#define ERROR_WORD_NOT_FOUND           0
#define ERROR_NO_MEM                   1
#define ERROR_FFI_ARGUMENTS            2
#define ERROR_FFI_LIBRARY_NOT_FOUND    3
#define ERROR_FFI_FUNCTION_NOT_FOUND   4
#define ERROR_STACK                    5
#define ERROR_CLOSE_STDIN              6
#define ERROR_QUOTE_TOO_BIG            7
